#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook "osx", :github => "pivotal-sprout/osx"

%w(rbenv ruby git base osx-apps osx-settings rubymine homebrew terminal postgresql ssh).map do |pkg|
  cookbook "sprout-#{pkg}", :github => "pivotal-sprout/sprout-#{pkg}"
end

cookbook "python"
cookbook "tool-customizations", path: "site-cookbooks/tool-customizations"
